### ISSUE TITLE
[QUESTION] Use of Relative Root Option / Files are not Replaced

### ISSUE THREAD

**Issue by 360disrupt** [OverZealous/gulp-cdnizer#30] opened 2018-03-01 08:41 UTC
How to set the relative path in order to replace the included js files?

Folder structure:

- src
  - frontend
    - index.html
- dist
  - frontend
    - index.html
- bower_components

 ```
return gulp.src(paths.tmp + '/serve/**/index.html')
    .pipe($.inject(partialsInjectFile, partialsInjectOptions))
    .pipe($.cdnizer({
      nodeModules: false,
      allowMin: true,
      relativeRoot: 'frontend/', //tried 'dist/frontend/' & none
      files: ['../../bower_components*'] //also tried ['**/*'] & ['**/*.js']
    }))
   ...
  .pipe(gulp.dest(paths.dist + '/'))
```

Compiled index.html
```
    <!-- bower:js -->
    <script src="../../bower_components/jquery/dist/jquery.js"></script>
    <script src="../../bower_components/angular/angular.js"></script>
```

**Comment by OverZealous** [comment] 2018-03-01 14:12
This is the wrong repo for questions about cdnizer itself (this doesn't appear to be related to using it within Gulp).

I'm pretty sure this is a duplicate of [this bug](https://github.com/OverZealous/cdnizer/issues/20), which is an issue with an external library that we can't fix. I've included some suggestions there, or you can switch to using absolute paths, which don't have the same issues.

**Closed by OverZealous** 2018-03-01 14:12 UTC
